parameters:
    ezpublish_rest.security.authentication.listener.session.class: eZ\Publish\Core\REST\Server\Security\RestAuthenticator
    ezpublish_rest.security.authentication.logout_handler.class: eZ\Publish\Core\REST\Server\Security\RestLogoutHandler
    ezpublish_rest.security.authentication.basic.class: eZ\Publish\Core\REST\Server\Security\BasicAuthenticator
    ezpublish_rest.security.authentication.provider.pre_auth.class: eZ\Publish\Core\REST\Server\Security\RestRepositoryAuthenticatorProvider

    ezpublish_rest.security.user_provider.class: eZ\Publish\Core\REST\Server\Security\RestApiUserProvider
    
    ezpublish_rest.security.csrf.token_manager.class: eZ\Publish\Core\REST\Server\Security\CsrfTokenManager
services:
    # Following service will be aliased at compile time to "ezpublish_rest.session_authenticator" by the Security factory.
    ezpublish_rest.security.authentication.listener.session:
        class: "%ezpublish_rest.security.authentication.listener.session.class%"
        arguments:
            - "@security.token_storage"
            - "@security.authentication.manager"
            - ~ # Will be replaced at compile time by security provider key
            - "@event_dispatcher"
            - "@ezpublish.config.resolver"
            - "@session.storage"
            - "@?logger"
        abstract: true

    ezpublish_rest.security.authentication.logout_handler:
        class: "%ezpublish_rest.security.authentication.logout_handler.class%"
        arguments:
            - '@ezpublish.config.resolver'

    ezpublish_rest.security.csrf.token_manager:
        class: '%ezpublish_rest.security.csrf.token_manager.class%'
        arguments:
            - '@?security.csrf.token_generator'
            - '@?security.csrf.token_storage'
            - '@?request_stack'

    ezpublish_rest.security.authentication.basic:
        class: '%ezpublish_rest.security.authentication.basic.class%'
        arguments:
            - '@ezpublish_rest.security.authentication.provider.pre_auth'


    ezpublish_rest.security.user_provider:
        class: '%ezpublish_rest.security.authentication.basic.class%'
        parent: 'ezpublish.security.user_provider'
    
    # The security compiler pass adds a call to the setRepository method 'security.authentication.provider.dao' that in turn gets
    # inherited by this service.
    ezpublish_rest.security.authentication.provider.pre_auth:
        class: '%ezpublish_rest.security.authentication.provider.pre_auth.class%'
        parent: 'security.authentication.provider.dao'
